app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name = "apps"
#name space
urlpatterns = [
    path('',views.index,name='indexApp'),
    path('add/', views.add_post, name='postnew'),
    path('sucess/', views.save_form_sucess, name='save_form_sucess'),
    path('fail/', views.save_form_fail, name='save_form_fail'),
    path("<int:pk>", views.item, name="item"),
    path('<int:pk>', views.delete, name='delete'),# delete new post
    path('policy/',views.policy,name="policy"),
    path('warning/', views.warning, name="warning"),
    path('donate/', views.donate, name="donate"),
    path('donate-complete/', views.donate_complete, name='donate-completed'),
    path('terms/', views.terms, name="terms"),
    path('introduce/', views.introduce, name="introduce"),
    path('report/',views.report,name="reportError"),
    path("search/",views.search, name="searchAdvance"),
    path("display_new/", views.displaynew, name="displaynew"),
    path("new-search/", views.newsearch, name="new-search"),
    path("new-pets/", views.searchpets, name="search-pets"),
    path("new-people/", views.searchpeople, name="search-people"),
    path("news/", views.news, name="news"),
    path("posts", views.posts, name="posts"),
    path("searchbar/", views.searchBar, name='search-bar'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path("<int:pk>", views.update, name="update"),
    path("updaterecord/<int:pk>", views.updaterecord, name="updaterecord" ),
    path("reset_password/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('', views.index, name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms import TextInput, EmailField, PasswordInput

class RegistrationForm(forms.Form):

    username = forms.CharField(label='Tài khoản', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email',widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Mật khẩu', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Nhập lại Mật khẩu', widget=forms.TextInput(attrs={'class': 'form-control'}))


    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mật khẩu không hợp lệ.")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("Tên tài khoản có kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("taì khoản đã tồn tại ")

    def save(self):
        User.objects.create_user(username=self.cleaned_data["username"], email=self.cleaned_data["email"],
                                 password=self.cleaned_data["password1"])



    


users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate , login, logout
from django.urls import reverse
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404

def update(request, pk):
    mymember= get_object_or_404(User, pk=pk)
  
    return render(request, 'users/update.html', {
        'mymember': mymember
    })
    
def updaterecord(request, pk):
    
    email = request.POST['email']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']

    member = get_object_or_404(User, pk=pk)
    member.first_name = first_name
    member.last_name = last_name
    member.email = email
    member.save()
    return HttpResponseRedirect(reverse('users:index'))

    


def registerPage(request):
    pass
    # form = UserCreationForm()
    # if request.method == "POST":
    #     form = UserCreationForm(request.POST)
    #     if form.is_valid():
    #         form.save()
            
    # context = {'form': form}
    # return render(request, 'users/register1.html', context)
@login_required
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            
            login(request, user)
            
            return HttpResponseRedirect(reverse("apps:indexApp"))
        else:
            messages.error(request, "Your username or password are not correct. Try login again.!")
            render(request, "users/login.html", {
                "message": "Invalid Credentials"
            })
    
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    messages.success(request, "you log out successful!")
    return render(request, "users/login.html", {
        "message": "Logged Out"
    })


def resetpwd(request):
    return render(request,'users/reset_password.html')


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.cleaned_data['username']
            form.cleaned_data['email']
            form.cleaned_data['password1']
            form.save()
            messages.success(request, "You have create an account successful. Try login now.")
            return HttpResponseRedirect(reverse('users:index'))
        else:
            messages.error(request, "you're information is not valid, try again.")
            return render(request, 'users/register.html', {
                'form': form
            })

    return render(request, 'users/register.html',{
            'form': RegistrationForm()
        })




    
    

users/templates/users/home.html
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!--Bootstrap CSS-->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        {% load crispy_forms_tags %}  
        <!--Contact form-->
        ...
    

    <!-- Optional Javascript -->
    <div>
      <h1>Contact</h1>
      <h4>Contact us directly if you have any questions</h4>
      <p>
        Please write your name, email address and a message below if you have any questions.
        One of our staff members will be happy to contact you directly and answer your questions as soon as possible. 
      </p>
      <form method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-6 col-md-12">
              {{form.first_name|as_crispy_field}}
            </div>
            <div class="col-lg-6 col-md-12">
              {{form.last_name|as_crispy_field}}
            </div>
          </div>
          <div class="row">
              {{form.email_address|as_crispy_field}}
          </div>
          <div class="row">
              {{form.comment|as_crispy_field}}
          </div>
              <button type="submit">Submit</button>
          </form>
      </div>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

users/templates/users/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title%}
        {% endblock %}
    </title>

    <style>


#detail {
  display: flex;
  width: 750px;
  background-color: #fff;
  padding: 0;
  border-radius: 5px;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  color: black;
}

   .success {
    padding: 10px;
    background: AliceBlue;
    text-align: center;
    text-transform: capitalize;
    font-size: larger;
    border-radius: 5px;
    margin-bottom: 2px;
 
  } 
  .error {
    padding: 10px;
    background: AntiqueWhite;
    text-align: center;
    text-transform: capitalize;
    font-size: larger;
    border-radius: 5px;
    margin-bottom: 2px;
   
  }

 

   
    </style>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <link href="{% static 'users/styles.css' %}" rel="stylesheet">
    <link href="{% static 'users/style_new.css' %}" rel="stylesheet">
    
		<script src="https://kit.fontawesome.com/d9cb093daf.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'app/footer-styles.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    
    {% comment %} <script src="{% static 'users/scripts.js'%}"></script> {% endcomment %}
</head>
<body  style="background-color: #ffff">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark" id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="javascript:void(0)">
          <img src="{% static 'app/5Lost.png' %}" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:indexApp' %}">Trang chủ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:searchAdvance'%}">Tìm kiếm </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)">Blog</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'apps:search-bar' %}" method="post" >
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search post new" name="searched">
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>



  <div class='container-fluid pt-5' >
        <div class='row'>
            <div class='col-sm-4 col-lg-3'>

            </div>
<!--            *********************************************-->
             <div class='col-sm-4 col-lg-6  ' >
              {% block wrapper %}
                 {% endblock %}
            </div>
<!--            *********************************-->
             <div class='col-sm-4 col-lg-3'>

            </div>
         



</body>
</html>


users/templates/users/login.html
{% extends 'users/layout.html' %}
{% load static %}
{% block title %}
    Timdothatlac.vn
{% endblock %}

{% block wrapper %}
                {%if messages %}
                    {% for message in messages %}
                        <div class="{{message.tags}}" >{{message }}</div>
                    {%endfor%}
                {%endif%}
        
         <div class="wrapper" >
          
        <div class="left-content">
            <h3>Login Account</h3>
             <div class="icons_form">
                 <span> <a href="{% url 'social:begin' 'google-oauth2' %}"><i class="fa-brands fa-google"></i></a></span>
                <span> <a href="{% url 'social:begin' 'facebook' %}"><i class="fa-brands fa-facebook-f fb_icon"></i></a></span>
                <span><i class="fa-brands fa-twitter"></i></span>
                <span><i class="fa-brands fa-linkedin-in"></i></span>
             </div>
            <form action="{% url 'users:login' %}" method='post' class="form_group">
                {% csrf_token %}
                <div class="username">
                    <label for="exampleInputEmail1" class="form-label">Username:</label>
                    <input class="form-control", type="text", name="username", placeholder="User Name">
                </div>
                <div class="password">
                    <label for="exampleInputPassword1" class="form-label">Password:</label>
                    <input type="password", name='password',placeholder="Pass word", class="form-control" >
                </div>


                <input type="submit", value='Login' class="btn_submit">
                <p class="forget_password"><a href="http://127.0.0.1:8000/accounts/password_reset/">Forgot your password?</a></p>
                <p id="btn_register"><a href="{% url 'users:register' %}">Register</a></p>
            </form>

        </div>
        <div class="image">
         <img src="{% static 'users/background_login.png'%}" alt="">
        </div>


    </div>

{% endblock %}

users/templates/users/register.html

{% extends 'users/layout.html' %}

{% load static %}

{% block title %}
    Register
{% endblock %}

{% block wrapper %}
   
 <div class="wrapper" >
                {%if messages %}
                    {% for message in messages %}
                        <div class="{{message.tags}}" >{{message }}</div>
                    {%endfor%}
                {%endif%}
        <div class="left-content">
            <h3>Create Account</h3>
             <div class="icons_form">
                <span><i class="fa-brands fa-google"></i></span>
                <span><i class="fa-brands fa-facebook-f fb_icon"></i></span>
                <span><i class="fa-brands fa-twitter"></i></span>
                <span><i class="fa-brands fa-linkedin-in"></i></span>
             </div>
       <form action="{% url 'users:register' %}" method="POST">

           {% csrf_token %}
           {{form.as_p}}

           <input type="submit" value="Đăng ký" class="btn btn-primary">
       </form>
            <p> Already have an account?<a href="{% url 'users:login'%}"> login</a></p>
            </div>
        <div class="image">
         <img src="{% static 'users/background_login.png'%}" alt="">
        </div>


    </div>

<!--   </body>-->
<!--</html>-->
       {% endblock %}

users/templates/users/temper.html
{% extends 'users/layout.html' %}
{% load static %}
{% block title %}
    Timdothatlac.vn
{% endblock %}

{% block wrapper %}
         <div class="  wrapper">
        <div class="left-content">
            <h3>Create Account</h3>
             <div class="icons_form">
                <span><i class="fa-brands fa-google"></i></span>
                <span><i class="fa-brands fa-facebook-f fb_icon"></i></span>
                <span><i class="fa-brands fa-twitter"></i></span>
                <span><i class="fa-brands fa-linkedin-in"></i></span>
             </div>
            <form action="{% url 'users:login' %}" method='post' class="form_group">
                {% csrf_token %}
                <div class="username">
                    <label for="exampleInputEmail1" class="form-label">Username:</label>
                    <input class="form-control", type="text", name="username", placeholder="User Name">
                </div>
                <div class="password">
                    <label for="exampleInputPassword1" class="form-label">Password:</label>
                    <input type="password", name='password',placeholder="Pass word", class="form-control" >
                </div>


                <input type="submit", value='Login' class="btn_submit">
                <p class="forget_password"><a href="{% url 'users:resetpwd'%}">Forgot your password?</a></p>
                <p id="btn_register"><a href="{% url 'users:register' %}">Register</a></p>
            </form>

        </div>
        <div class="image">
         <img src="{% static 'users/background_login.png'%}" alt="">
        </div>


    </div>

{% endblock %}

users/templates/users/update.html
{% extends 'users/layout.html' %}
{% load static %}
{% block title %}
    Update ifo user
{% endblock %}
{% block wrapper %}

   <h1>Cập nhật thông tin </h1>
      
    <form action="updaterecord/{{ mymember.id }}" method="post">
    {% csrf_token %}
     

    Email:<br>
    <input name="email" value="{{ mymember.email }}" class="form-control">
    <br><br>

    First name<br>
    <input name="first_name" value="{{ mymember.first_name}}" class="form-control">
    <br><br>

     Last name<br>
    <input name="last_name" value="{{ mymember.last_name }}" class="form-control">
    <br><br>

   
    <input type="submit" value="Submit" class="btn btn-secondary">
    </form>
{% endblock %}

users/templates/users/user.html
{% comment %} {% extends 'users/layout.html' %}

{% block wrapper %}
    <div id="detail" >
            <h1>User {{ request.user.first_name }}</h1>
            <ul>
                <li >Username: {{ request.user.username }}</li>
                <li>Email: {{ request.user.email}}</li>

            </ul>

            <a href="{% url 'users:logout' %}"> Log Out</a>
        </div> 

    

{% endblock %} {% endcomment %}
{%load static %}
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>profile</title>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="profile-styles.css">
        <link href="{% static 'users/profile-styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark" id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="javascript:void(0)">
          <img src="{% static 'app/5Lost.png' %}" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:indexApp' %}">Trang chủ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:searchAdvance'%}">Tìm kiếm </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)">Blog</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'apps:search-bar' %}" method="post" >
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search post new" name="searched">
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

        <div class='card'>
            <img src="{% static 'users/background.jpg'%}" alt="image" style='width:100%'>
            <h1>{{ request.user.username }}</h1>
        <p class="title">Email: {{ request.user.email}}</p>
        <p class="title">First name: {{ request.user.first_name}}</p>
        <p class="title">Last name: {{ request.user.last_name}}</p>
        
           <p> <a class='log' href="{% url 'users:logout' %}"> Log Out</a><p>
            <a href="{% url 'users:update' request.user.id %}"> <button  class="btn btn-secondary" type="button"> Cập nhật thông tin</button> </a>

    
        </div>
    </body>
</html>