app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name = "apps"
#name space
urlpatterns = [
    path('',views.index,name='indexApp'),
    path('add/', views.add_post, name='postnew'),
    path('sucess/', views.save_form_sucess, name='save_form_sucess'),
    path('fail/', views.save_form_fail, name='save_form_fail'),
    path("<int:pk>", views.item, name="item"),
    path('<int:pk>', views.delete, name='delete'),# delete new post
    path('policy/',views.policy,name="policy"),
    path('warning/', views.warning, name="warning"),
    path('donate/', views.donate, name="donate"),
    path('donate-complete/', views.donate_complete, name='donate-completed'),
    path('terms/', views.terms, name="terms"),
    path('introduce/', views.introduce, name="introduce"),
    path('report/',views.report,name="reportError"),
    path("search/",views.search, name="searchAdvance"),
    path("display_new/", views.displaynew, name="displaynew"),
    path("new-search/", views.newsearch, name="new-search"),
    path("new-pets/", views.searchpets, name="search-pets"),
    path("new-people/", views.searchpeople, name="search-people"),
    path("news/", views.news, name="news"),
    path("posts", views.posts, name="posts"),
    path("searchbar/", views.searchBar, name='search-bar'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path("<int:pk>", views.update, name="update"),
    path("updaterecord/<int:pk>", views.updaterecord, name="updaterecord" ),
    path("reset_password/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('', views.index, name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/donate.html
{% extends 'app/frame.html' %}
{% load static %}

{% comment %} {% block title %}
Ủng hộ dự án
{% endblock %} {% endcomment %}

{% block content %}
<div class="container">
    <div class="wrapper">
        <div class="row">

            <div class="col-lg-6">
                <h4>
                    Ủng hộ dự án
                </h4>
                <b>
                    Timdothatlac.vn là một dự án cộng đồng được tạo nên để giúp mọi người có thể đăng tin tìm đồ, tìm
                    thú cưng thất lạc, nhắn tìm người thân.
                </b>
                <img src="{% static 'app/donate.jpg'%}" alt="" style='height: 100%; width: 100%; object-fit: contain'>
                <p>
                    Chúng tôi không thu phí khi người dùng đăng tin.
                </p>
                <p>
                    Nếu bạn cảm thấy dự án có ích , hãy ủng hộ chúng tôi để đội ngũ phát triển dự án có thể duy trì và
                    phát triển các tính năng mới cho dự án.
                </p>
                <b>
                    Thông tin tài khoản nhận:
                </b>
                <ul>
                    <li>Số tài khoản: </li>
                    <li>Ngân hàng: </li>
                    <li>Chi nhánh: </li>
                    <li>Chủ tài khoản: </li>
                </ul>
                <p>
                    Trân trọng !
                </p>
                <p>
                    Chia sẻ:
                </p>
            </div>
            <div class="col-lg-3">

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/error.html
<!DOCTYPE html>
<html>
    <head>
    <title>Error</title>
    </head>
    <body>
        <h1>Invalid information</h1>
    </body>
</html>

app/templates/app/frame.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
    <head>
		
        <script src="https://kit.fontawesome.com/ea6ab068fd.js" crossorigin="anonymous"></script>
        <title> {% block title %} {% endblock %} </title>
        <link href="{% static 'app/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

		<script src="https://kit.fontawesome.com/d9cb093daf.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        
		{% block head%}
		{% endblock %}

		<style>
			footer{
				position: relative;
				
			}
			.footer-dark {
				padding:50px 0;
				color:#f0f9ff;
				background-color:#282d32 ;
			  }
			  
			  .footer-dark h3 {
				margin-top:0;
				margin-bottom:12px;
				font-weight:bold;
				font-size:16px;
			  }
			  
			  .footer-dark ul {
				padding:0;
				list-style:none;
				line-height:1.6;
				font-size:14px;
				margin-bottom:0;
			  }
			  
			  .footer-dark ul a {
				color:inherit;
				text-decoration:none;
				opacity:0.6;
			  }
			  
			  .footer-dark ul a:hover {
				opacity:0.8;
			  }
			  
			  @media (max-width:767px) {
				.footer-dark .item:not(.social) {
				  text-align:center;
				  padding-bottom:20px;
				}
			  }
			  
			  .footer-dark .item.text {
				margin-bottom:36px;
			  }
			  
			  @media (max-width:767px) {
				.footer-dark .item.text {
				  margin-bottom:0;
				}
			  }
			  
			  .footer-dark .item.text p {
				opacity:0.6;
				margin-bottom:0;
			  }
			  
			  .footer-dark .item.social {
				text-align:center;
			  }
			  
			  @media (max-width:991px) {
				.footer-dark .item.social {
				  text-align:center;
				  margin-top:20px;
				}
			  }
			  
			  .footer-dark .item.social > a {
				font-size:20px;
				width:36px;
				height:36px;
				line-height:36px;
				display:inline-block;
				text-align:center;
				border-radius:50%;
				box-shadow:0 0 0 1px rgba(255,255,255,0.4);
				margin:0 8px;
				color:#fff;
				opacity:0.75;
			  }
			  
			  .footer-dark .item.social > a:hover {
				opacity:0.9;
			  }
			  
			  .footer-dark .copyright {
				text-align:center;
				padding-top:24px;
				opacity:0.3;
				font-size:13px;
				margin-bottom:0;
			  }
			  
			
			
			  
		</style>


    </head>

	<body >
		 <div class="main-index" style="height:100vh" >
			{% include 'app/navbar.html' %}
			<div class="container">
				<div class="wrapper">
					<div class="row">
						<div class="col-lg-3 taskbar">
							<a href="{% url 'apps:postnew'%}" class="item-icon">
								<i class="fas fa-upload"></i>
								Đăng tin
							</a>
							<a href="{% url 'apps:new-search' %}" class="item-icon">
								<i class="far fa-frown-open"></i>
								Tin cần tìm
							</a>
							<a href="{% url 'apps:displaynew'%}" class="item-icon">
								<i class="fas fa-box"></i>
								Tin nhặt được
							</a>
							<a href="{% url 'apps:search-pets' %}" class="item-icon">
								<i class="fas fa-paw"></i>
								Thú cưng
							</a>
							<a href="{%url 'apps:search-people'%}" class="item-icon">
								<i class="far fa-user"></i>
								Tìm người
							</a>
							<a href="{% url 'apps:searchAdvance'%}" class="item-icon">
								<i class="fas fa-search"></i>
								Tìm kiếm nâng cao
							</a>
							<a href="#" class="item-icon">
								<i class="fas fa-phone-slash"></i>
								Danh sách SDT lừa đảo
							</a>
							<br>
							<a href="{% url 'apps:news' %}" class="item-icon">
								<i class="fas fa-newspaper"></i>
								Tin tức
							</a>
							<a href="{% url 'apps:introduce' %}" class="item-icon">
								<i class="fas fa-info"></i>
								Giới thiệu
							</a>
							<a href="{% url 'apps:donate' %}" class="item-icon">
								<i class="fas fa-dollar-sign"></i>
								Ủng hộ dự án
							</a>
							<a href="{% url 'apps:policy' %}" class="item-icon">
								<i class="fas fa-shield-alt"></i>
								Chính sách bảo mật
							</a>
							<a href="{% url 'apps:terms' %}" class="item-icon">
								<i class="fas fa-book"></i>
								Điều khoản sử dụng
							</a>
							<a href="{% url 'apps:warning' %}" class="item-icon">
								<i class="fas fa-shield-alt"></i>
								Cảnh báo lừa đảo
							</a>
							<a href="{% url 'apps:reportError' %}" class="item-icon">
								<i class="fas fa-bug"></i>
								Báo lỗi
							</a>
						</div>
						<div class="col-lg-9">
							<p>

							   {% block content %}
							   {% endblock %}


							</p>
						</div>
					</div>
				</div>
			</div>
		

			<div class="footer-dark">
				<footer>
					<div class="container">
						<div class="row">
							<div class="col-sm-6 col-md-4 item">
								<h3>Go to</h3>
								<ul>
									<li><a href="{% url 'apps:indexApp'%}"><p><i class="icon ion-home"></i> Home </p></a></li>
									<li><a href="#"><p><i class="icon ion-ios-book"></i> Blog</p></a></li>
									<li><a href="{% url 'apps:searchAdvance'%}"><p><i class="icon ion-search"></i> Search</p></a></li>
								</ul>
							</div>
							<div class="col-sm-6 col-md-4 item">
								<h3>About</h3>
								<ul>
									<li><a href="#"><p><i class="fas fa-city"></i> Company </p></a></li>
									<li><a href="#"><p><i class="fas fa-users"></i> Team </p></a></li>
									<li><a href="#"><p><i class="fas fa-car"></i> Terms & Policy </p></a></li>
								</ul>
								
							</div>
							<div class="col-md-4 item text">
								<h3>Contact</h3>
								<p><i class="icon ion-location"></i>  Đường Hàn Thuyên, khu phố 6 P, Thủ Đức, Thành phố Hồ Chí Minh </p>
								<p><i class="icon ion-ios-telephone"></i>  +84xxxxxxxxx  </p>
								<p><i class="icon ion-email"></i> xxxxxxxxx@uit.edu.vn  </p>
								
								
							</div>
							
							<div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
						</div>
						<p class="copyright">Timdothatlac©2022</p>
					</div>
				</footer>
			</div>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

app/templates/app/index.html
{% extends 'app/frame.html'%}
{% comment %} 
 <!-- title = models.CharField("Tiêu đề", max_length = 200)
    postInfo = models.CharField("Kiểu tin tức",max_length = 10,choices=_postInfo,blank=True)
    typeItem = models.CharField("Phân loại đồ", max_length = 50)
    adrLost = models.CharField("Địa điểm mất",max_length=200)
    image = models.ImageField( upload_to='images/', height_field=None, width_field=None, max_length=None) 
    content = models.CharField("Nội dung", max_length=500)
    fullname = models.CharField("Họ tên",blank = True, max_length = 100)
    address = models.CharField("Địa chỉ",blank = True, max_length = 200)
    phoneNum = models.CharField("Số điện thoại",blank =  True, max_length = 10)
    email = models.EmailField(("Email"),blank = True, max_length=254)

     --> {% endcomment %}

  
{% block content %}

    <h1>Tin mới nhất  </h1>
     {%if messages %}
    {% for message in messages %}
        <div class="{{message.tags}}" >{{message }}</div>
    {%endfor%}
    {%endif%}
    {% comment %} <ul class="list-group list-group-flush">
  <li class="list-group-item">An item</li>
  <li class="list-group-item">A second item</li>
  <li class="list-group-item">A third item</li>
  <li class="list-group-item">A fourth item</li>
  <li class="list-group-item">And a fifth one</li>
</ul> {% endcomment %}
    <div class="list-group ">
      {% for item in items %}
         <a class="list-group-item list-group-item-action list-group-item-secondary" href="{% url 'apps:item' item.id %}">
           <b>{{ item.title }}</b> 
           {%if item.location%}
            <p> Vị trí: {{item.location}} </p> 
            {%endif%}
          </a>
      {% endfor %}
    </div>
    <br/><br/>
    {% comment %} {{items}}<br/>

    Has Previous: {{items.has_previous}}<br/>
    Has Next: {{items.has_next}}
    Current Page: {{ items.number}}<br/>
    Number of pages: {{items.paginator.num_pages}} {% endcomment %}
    <hr><br/><br/>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if items.has_previous %}
        <li class="page-item"> <a href="?page1" class="page-link" > &laquo First </a> </li>
        <li class="page-item"> <a class="page-link" href="?page={{ items.previous_page_number }}"> previous</a> <li>
        {%endif%}

        <li class="page-item disabled"> <a class="page-link" href="#"> Page {{items.number}} of {{items.paginator.num_pages}} </a><li>
        
         
          {%for i in nums %}

            <li class="page-item" > <a class="page-link" href="?page={{forloop.counter}}"> {{ forloop.counter }}</a></li>
          {% endfor %}


        {% if items.has_next %}
      <li class="page-item"> <a class="page-link" href="?page={{ items.next_page_number }}"> next</a> </li>

        <li class="page-item"> <a  class="page-link" href="?page={{items.paginator.num_pages}}"> Last &raquo</a> </li>
        {% endif %}

      <ul>
    </nav>




  
{% endblock %}

app/templates/app/item.html
{% extends 'users/layout.html' %}
{% load static %}
{% block title %}
    Timdothatlac.vn
{% endblock %}

{% block wrapper %}

<div id="detail" >
    <ul class="list-group list-group-flush">
        {% comment %} <li>Title {{ item.title }}</li>
       <li>Type of items: {{item.typeItem}}</li>
       <li>Kind of news : {{ item.postInfo }}</li>
       <li>Address: {{ item.location }}</li>
       <li>Content: {{ item.postInfo }}</li>
       <li>name  post: {{ item.fullname }}</li>
       <li>phone number: {{ item.phoneNum }}</li>
       <li>Email: {{ item.postInfo }}</li> {% endcomment %}
     

          {%if item.title%}
            <li class="list-group-item"> <b>Tiêu đề:</b>  {{ item.title }}</li>
          {% endif %}
          {% if item.content %}
            <li class="list-group-item"><b>Nội dung:</b>  {{item.content}}</li>
          {% endif %}

           {% if item.image %}
            <li class="list-group-item"><b>Hình ảnh </b>  {{item.image}}</li>
          {% endif %}

          
          {%if item.location  %}
            <li class="list-group-item"><b>Địa điểm thất lạc:</b>  {{ item.location }}</li>
          {% endif %}
        
          {%if item.email %}
            <li class="list-group-item"><b>email liên hệ: </b>  {{ item.email }}</li>
          {%endif%}
          {%if item.phone%}
            <li class="list-group-item"><b>Số điện thoại liên hệ:</b> {{ item.phone }}</li>
          {%endif%}

          {%if item.date_time%}
            <li class="list-group-item"><b>Thời gian đăng tin: </b> {{ item.date_time }}</li>
          {%endif%}
          {% if item.image %}
            <li class="list-group-item"><img src="/app/media/{{item.image}}" class="img" style="width 80px; height 80px;"></li>
          {% endif %}
          {% comment %} Delete or update items {% endcomment %}
          
          

          <li class="list-group-item">
            <h2>Comment</h2>

           {% for comment in item.comments.all %}
           <div class="list-group">
           
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1" ><strong>{{comment.user}}</strong><h5>
              <small class="text-muted"><p>{{comment.date}}</p></small>
              <p>{{comment.content|linebreaks}}</p>
              </div>
           
            </div>
          {% endfor %}

          {%if user.username %}
          <form action="{% url 'apps:item' item.pk %}" method='POST'>
            {%csrf_token%}
            <p> <label> Bình Luận</p>
              {{form.content}}
              <br/>
              <input class="btn btn-primary" type="submit" value="Bình Luận">
          {% endif %} 

          {%if not user.username %}
                <h4>Đăng nhập để bình luận</h4>
              <a href="{%url 'users:login'%}"> <button  class="btn btn-secondary" type="button"> Đăng nhập</button> </a>

          {% endif %}
          
          </li>

         

    </ul

     
  </div> 

  
 

{% endblock %}

app/templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title%}
        {% endblock %}
    </title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <link href="{% static 'app/styles_layout.css' %}" rel="stylesheet">
    <script src="{% static 'app/myfirst.js' %}"></script>

     <script src="https://kit.fontawesome.com/d9cb093daf.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'app/footer-styles.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
   
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark" id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="javascript:void(0)">
          <img src="{% static 'app/5Lost.png' %}" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:indexApp' %}">Trang chủ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:searchAdvance'%}">Tìm kiếm </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)">Blog</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="text" placeholder="Search">
        <button class="btn btn-primary" type="button">Search</button>
      </form>
    </div>
  </div>
</nav>



  <div class='container-fluid pt-5' >
        <div class='row'>
            <div class='col-sm-4 col-lg-3'>

            </div>
<!--            *********************************************-->
             <div class='col-sm-4 col-lg-6  ' >
              {% block wrapper %}
                 {% endblock %}
            </div>
<!--            *********************************-->
             <div class='col-sm-4 col-lg-3'>

            </div>

          <footer>
             <div class="footer-content">
            <h3> Tìm đồ thất lạc</h3>
            <p>Tìm đồ thất lạc nhanh chóng hiệu quả </p>
            <ul class='socials'>
                <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa-brands fa-github"></i></a></li>
                <li><a href="#"><i class="fa-brands fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
                <li><a href="#"><i class="fa-brands fa-reddit"></i></a></li>
            </ul>
        </div>
        <div class="footer-bottom">
            <p>copyright&copy;2022 </p>
        </div>
    </footer>



</body>
</html>


app/templates/app/navbar.html
{% load static %}
<div class="container navbar" >
    <div class="wrapper">

        <a href="{% url 'apps:indexApp'%}" class="col-sm-6 col-lg-3"><img src="{% static 'app/homelogo.png' %}" alt="Home Page" class="homelogo"></a>
        <div class="col-sm-6 col-lg-6 ">
            
        </div>
        <div class="col-sm-6 order-sm-2 col-lg-3">
            <ul class="nav	">
                <li>
                    <a href="{% url 'apps:postnew'%}">
                        <i class="fas fa-plus-circle"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-bell"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:index' %}">
                        <abbr title="Login or Register" ><i class="fas fa-user-circle" > </i></abbr>
                    </a>
                </li>
            </ul>

        </div>
    </div>


</div>

app/templates/app/payment_page.html
{%load static %}
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Donate me</title>
        <!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <style>
        body {
            background-color: #fff;
        }
        .text-center {
            {% comment %} background-color: white;
            width:500px;
            margin-top: 50px;
            boder {% endcomment %}
         
         width: 750px;
         background-color: #ffff;
         margin-top:20px;   
         padding: 20px;
         border-radius: 5px;
         box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
            

               
        }
    </style>
    
    <script src="https://www.paypal.com/sdk/js?client-id=AU4sJMCBXJXuFFaHRXJtf9zMSmSOYGJ5Aj9FHjrxa6lWUtAFrgZ-zOiAahxApN9uyzKeWg98yPXwOGYK&currency=USD&intent=capture&enable-funding=venmo" data-sdk-integration-source="integrationbuilder"></script>   
    <script> 
         const paypalButtonsComponent = paypal.Buttons({
              // optional styling for buttons
              // https://developer.paypal.com/docs/checkout/standard/customize/buttons-style-guide/
              style: {
                color: "gold",
                shape: "rect",
                layout: "vertical"
              },

              // set up the transaction
              createOrder: (data, actions) => {
                  // pass in any options from the v2 orders create call:
                  // https://developer.paypal.com/api/orders/v2/#orders-create-request-body
                  const createOrderPayload = {
                      purchase_units: [
                          {
                              amount: {
                                  value: "5"
                              }
                          }
                      ]
                  };

                  return actions.order.create(createOrderPayload);
              },

              // finalize the transaction
              onApprove: (data, actions) => {
                  const captureOrderHandler = (details) => {
                      const payerName = details.payer.name.given_name;
                      console.log('Transaction completed');
                      window.location.replace("{% url 'apps:donate-completed' %}")
                  };

                  return actions.order.capture().then(captureOrderHandler);
              },

              // handle unrecoverable errors
              onError: (err) => {
                  console.error('An error prevented the buyer from checking out with PayPal');
              }
          });

          paypalButtonsComponent
              .render("#paypal-button-container")
              .catch((err) => {
                  console.error('PayPal Buttons failed to render');
              });
    </script>
    <body>
         <nav class="navbar navbar-expand-sm navbar-dark bg-dark" id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="javascript:void(0)">
          <img src="{% static 'app/5Lost.png' %}" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:indexApp' %}">Trang chủ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'apps:searchAdvance'%}">Tìm kiếm </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)">Blog</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
        <div class='container text-center'>

            <h1>Feel free to donate</h1>
            <br>
            <p>Support me if you enjoy the content that I am providing.</p>

             <div id="paypal-button-container"></div>
            
        </div>
    </body>
</html>

app/templates/app/post.html
{% extends 'app/layout.html' %}

{% block title %}
Form post new
{% endblock %}



{% block wrapper %}

<div class="container wrapper" >

    <form action="." method="post" >

        {% csrf_token %}
        {{ form.as_p}}
    </br>
        <input type="submit" value="Submit" class="btn btn-primary" id="submit-post">
    </form>

</div>

{% endblock %}

app/templates/app/save_form_sucess.html
{% extends 'users/layout.html' %}
{% load static %}
{% block title %}
    Timdothatlac.vn
{% endblock %}

{% block wrapper %}

       <h1 style='color:green'>Save form sucess </h1>

{% endblock %}i